import { Roboto } from 'next/font/google'
import "../css/globals.css";

const font = Roboto({ weight: ['100'], style: ['normal'], subsets: ['latin'], display: 'swap' });


export const metadata = {
  title: "RW-App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="de">
      <body className={font.className}>{children}</body>
    </html>
  );
}
