import localFont from 'next/font/local';
import "../css/globals.css";


const font = localFont({ src: [{ path: '../fonts/Open_Sans/static/OpenSans-Light.ttf', weight: '300', style: 'normal' }] });


export const metadata = {
  title: "RW-App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
